const horseCard = document.getElementById('horseCard');
const weedCard = document.getElementById('weedCard');
const mindCard = document.getElementById('mindCard');
const horseCardback = document.getElementById('horseCardback');
const weedCardback = document.getElementById('weedCardback');
const mindCardback = document.getElementById('mindCardback');
const card1 = document.getElementById('card1');
const card2 = document.getElementById('card2');
const card3 = document.getElementById('card3');
const button = document.getElementById('button');

let display = [card1, card2, card3];

let displayShuffle = String(Math.floor(Math.random() * display.length));

let horseChoices = [
  "Admiral's Voyage",
  'Alpha',
  'American Flag',
  'Atomic Rain',
  'Backtalk',
  'Best Present Ever',
  'Bodemeister',
  'Cajun Beat',
  'California Chrome',
  'Celtic Ash',
  'Chocolate Candy',
  'Colorado King',
  'Commando',
  'Creative Cause',
  'Daddy Long Legs',
  'Daddy Nose Best',
  'Dance With Fate',
  'Danza',
  'Delhi',
  'Discreet Marq',
  'Done Talking',
  'Dunkirk',
  'Eight Thirty',
  'El Padrino',
  'Falling Sky',
  'Flying Private',
  'Frac Daddy',
  'Freesian Fire',
  'Genie',
  'Gentle Savage',
  'Ghost Zapper',
  'Gold Coin',
  'Golden Soul',
  'Greek Money',
  "Harry's Holiday",
  'Highest Honors',
  'Ice Box',
  'Indian Blessing',
  'Intense Holiday',
  'June Cleaver',
  'Kauai King',
  'Kid Cruz',
  'Kiss Moon',
  'Kona Gold',
  'Lady Secret',
  'Lemon Punch',
  'Liaison',
  'Luv Gov',
  'Magical Band',
  'Magic Hour',
  'Matterhorn',
  'Midnight Hawk',
  'Midnight Interlude',
  'Midnight Taboo',
  'Mind Bender',
  "Mind's Eyes",
  'Mister Hot Stuff',
  'Misty Morn',
  'Moccasin',
  'Mucho Macho Man',
  'Optimizer',
  'Orb',
  'Papa Clem',
  'Papa Jerry',
  'Peter Pan',
  'Please Explain',
  'Prime Directive',
  'Rachel Alexandra',
  'Rousing Sermon',
  'Sabercat',
  'Sacred Light',
  'Samraat',
  'Scottish Chieftain',
  'Scrimshaw',
  'Sizzling Gold',
  'Somali Lemonade',
  'Star Shoot',
  'Stay Thirsty',
  'St. Liam',
  'Stop Time',
  'Sugar Shock',
  'Summer Bird',
  'Summer Tan',
  'Sunshine Forever',
  'Sweet Vendetta',
  'Take The Points',
  'Terrain',
  'The Bard',
  'The Green Monkey',
  "Thor's Echo",
  'Thunder Gulch',
  'Token Special',
  'Twenty Grand',
  'Twilight Ridge',
  'Twinspired',
  'Union Rags',
  'Westside Bernie',
  'Wicked Strong',
  'Wildcat Red',
  'Wild Rush',
];

let horseShuffle = String(Math.floor(Math.random() * horseChoices.length));

let weedChoices = [
  'Accidental Tourist',
  'Ace of Spades',
  'Air Force One',
  'Allen Wrench',
  'American Dream',
  'Armageddon',
  'Aruel',
  'Asteroid',
  'Atmosphere',
  'Beehive',
  'Big Bud',
  'Bio-Jesus',
  'Black Domina',
  'Blue Bayou',
  'Blue Moon',
  'Brain Child',
  "Buddha's Sister",
  'Cherry Pie',
  'Chocolope',
  'Cracker Jack',
  'Dairy Queen',
  'Don Cristo',
  'Double Dream',
  'Dr. Grinspoon',
  'Dutch Treat',
  'Early Garage',
  'Early Girl',
  'Edelweiss',
  'El Jeffe',
  "Emperor's Cut",
  'Galactic Jack',
  'Glass Slipper',
  "God's Gift",
  'Godzilla',
  'Grand Hustle',
  'Grand Platinum',
  'Gun',
  'Hawaiian Fire',
  'Holy Grail',
  'Hubba Bubba',
  'Incredible Hulk',
  "Jack's Cleaner",
  'Jane Doe',
  'Jilly Bean',
  'Johnnie Walker',
  "Johnny's Tonic",
  "Joker's Revenge",
  'King Henry',
  'King Louis',
  "King's Bread",
  'L.A. Confidential',
  'Life Saver',
  'Liquid Butter',
  'Little Devil',
  'Loud Dream',
  'Louis XIII',
  'Low Rider',
  'Lucky Charms',
  'Medicine Man',
  'MK Ultra',
  'Morning Glory',
  'Morning Star',
  'Motorcity Whip',
  'Mr. Nice Guy',
  'Muchacho Man',
  "Neville's Maze",
  "Nevil's Wreck",
  'Orange Moon',
  'Outlaw',
  'Pennies From Heaven',
  'Pennywise',
  'Polite With a Punch',
  'Private Reserve',
  'Professor Chaos',
  'Purple Arrow',
  'Qrazy Train',
  'Rare Darkness',
  'Rated R',
  'Red Bull',
  'Richie Rich',
  'Rocklock',
  'Royal Dwarf',
  'Sapphire Star',
  'Shark Shock',
  'Shipwreck',
  'Smoke on the Water',
  'Soul Shine',
  'Sour Grapes',
  'Sunny Side Up',
  'Sunset Sherbert',
  'Sweet Tooth',
  'Tasmanian Devil',
  'Uncle Pete',
  'Watermelon Tormaline',
  'Whitaker Blues',
  'White Gold',
  'White Rhino',
  'White Russian',
  'Willies Wonder',
  'Yumboldt',
];

let weedShuffle = String(Math.floor(Math.random() * weedChoices.length));

let mindChoices = [
  'Accho',
  'Adios Amigos',
  'Albany New York',
  'Apples and Oranges',
  'Apricot',
  'Autumn Haze',
  'Avalanche',
  'Backlot Tour',
  'Ballyhoo',
  "Beethoven's Bust",
  "Bob's Your Uncle",
  'Boogeyman',
  'Buried Treasure',
  'Burnt Toast',
  'Cannery Row',
  'Captain America',
  'Chardonnay',
  'Charm Bracelet',
  "Cliff's Surprise",
  'Court Jester',
  'Crystal Ship',
  'Detour',
  'Dollar Bill',
  "Dolphin's Fin",
  'Double Barrel',
  'Double Jeopardy',
  'Dust-up',
  'Earth Worm',
  'Executive Suite',
  'Fog',
  'Fortunate Son',
  'Galaxy',
  'General Patton',
  'Ghost Town',
  'Giddy Up and Go',
  'Grape Nuts',
  'Grey Flannel',
  'Gupta',
  'High Tide',
  'Hummer',
  'Irish Eyes',
  'Jazz Age',
  'Joni Mitchell',
  'Lemonade',
  "Let's Hear It for the Boy",
  'Lieutenant Dan',
  'Long Tall Sally',
  'Low Tide',
  'Macho Nacho',
  'Milk & Cookies',
  "Miranda's Miracle",
  'Monkey Wrench',
  'Muldoon',
  'Par Excellence',
  'Pepper',
  "Poseidon's Trident",
  'Quote-Unquote',
  'Sacrificial Lamb',
  'Sealed With a Kiss',
  'Space Needle',
  'Stealth Bomber',
  'Strange Dawn',
  'Ukulele',
  'Uncle Ben',
  'Undeterred Goon',
  'Unlawful Entry',
  'Upstart',
  'Up Up and Away',
  'Waikiki Wave',
  'Weekender',
  'Holy Roller',
  'Inclement Weather',
  'Pop Rox',
  'Masquerade',
  "Monkey's Uncle",
  'Bible Thumper',
  'Shazam',
  'Photon Torpedo',
  "Devil's Workshop",
  'Frankenbutter',
  'Dung Beetle',
  'Black Astronaut',
  'Bowtie Rasta',
  'Carbon Credit',
  'High Fructose Porn Syrup',
  'Tiny Tim',
  'Free Raisin',
  'Chrysalis',
  'Porkchop Parody',
  "White Man's Burden",
  'Red Menace',
  'Bletchley Park',
  'High as Balls',
  'What a Crowd',
  'Boob Glue',
  'Culture Shock',
  'Marriage Sow',
  'Ka-ching!',
  'Alien Visitation',
  'Police Brutality',
];

let mindShuffle = String(Math.floor(Math.random() * mindChoices.length));

let draw = [
  horseChoices[horseShuffle],
  weedChoices[weedShuffle],
  mindChoices[mindShuffle],
];

function shuffle(draw) {
  var ctr = draw.length,
    temp,
    index;

  // While there are elements in the array
  while (ctr > 0) {
    // Pick a random index
    index = Math.floor(Math.random() * ctr);
    // Decrease ctr by 1
    ctr--;
    // And swap the last element with it
    temp = draw[ctr];
    draw[ctr] = draw[index];
    draw[index] = temp;
  }
  horseCard.innerHTML = horseChoices[horseShuffle];
  weedCard.innerHTML = weedChoices[weedShuffle];
  mindCard.innerHTML = mindChoices[mindShuffle];
  horseCardback.innerHTML = horseChoices[horseShuffle];
  weedCardback.innerHTML = weedChoices[weedShuffle];
  mindCardback.innerHTML = mindChoices[mindShuffle];
  return draw;
}
shuffle(draw);
